USE [master]
GO
/****** Object:  Database [JwtExample]    Script Date: 24/11/2021 16:17:42 ******/
CREATE DATABASE [JwtExample]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JwtExample', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JwtExample.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JwtExample_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JwtExample_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [JwtExample] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JwtExample].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JwtExample] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JwtExample] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JwtExample] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JwtExample] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JwtExample] SET ARITHABORT OFF 
GO
ALTER DATABASE [JwtExample] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [JwtExample] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JwtExample] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JwtExample] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JwtExample] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JwtExample] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JwtExample] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JwtExample] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JwtExample] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JwtExample] SET  DISABLE_BROKER 
GO
ALTER DATABASE [JwtExample] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JwtExample] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JwtExample] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JwtExample] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JwtExample] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JwtExample] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JwtExample] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JwtExample] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JwtExample] SET  MULTI_USER 
GO
ALTER DATABASE [JwtExample] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JwtExample] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JwtExample] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JwtExample] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JwtExample] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JwtExample] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [JwtExample] SET QUERY_STORE = OFF
GO
USE [JwtExample]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 24/11/2021 16:17:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[idRole] [int] NOT NULL,
	[name] [varchar](50) NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[idRole] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 24/11/2021 16:17:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[idUser] [int] NOT NULL,
	[login] [varchar](50) NULL,
	[pwd] [varchar](50) NULL,
	[name] [varchar](250) NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRole]    Script Date: 24/11/2021 16:17:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[idUser] [int] NOT NULL,
	[idRole] [int] NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[idUser] ASC,
	[idRole] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Role] FOREIGN KEY([idRole])
REFERENCES [dbo].[Role] ([idRole])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_Role]
GO
ALTER TABLE [dbo].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_User] FOREIGN KEY([idUser])
REFERENCES [dbo].[User] ([idUser])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserRole] CHECK CONSTRAINT [FK_UserRole_User]
GO
USE [master]
GO
ALTER DATABASE [JwtExample] SET  READ_WRITE 
GO
